### ISSUE TITLE
TypeError: requestActionPromise is not a function

### ISSUE THREAD

**Issue by alreadysabbir** [klis87/redux-saga-requests#254]
I'm using auto promise actions in a next.js `getInitialPorps` method. It gives following error at the server sometimes.

```shell
TypeError: requestActionPromise is not a function
    at /home/project/node_modules/redux-saga-requests/lib/middleware.js:41:13
    at /home/project/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1412:22
    at dispatch (/home/project/node_modules/redux/lib/redux.js:617:28)
    at /home/project/node_modules/@redux-saga/core/dist/chunk-774a4f38.js:126:12
    at /home/project/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:476:54
    at exec (/home/project/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:35:5)
    at flush (/home/project/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:91:5)
    at asap (/home/project/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:50:5)
    at runPutEffect (/home/project/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:472:3)
    at runEffect (/home/project/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1202:7)
    at digestEffect (/home/project/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1269:5)
    at next (/home/project/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1159:9)
    at currCb (/home/project/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1249:7)
    at runCallEffect (/home/project/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:543:5)
    at runEffect (/home/project/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1202:7)
    at digestEffect (/home/project/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1269:5)
The above error occurred in task sendRequest
    created by rootSaga
    created by rootSaga
Tasks cancelled due to error:
rootSaga
takeLatest(PASSWORD_LOGIN_SUCCESS, loginSuccessSaga)
takeLatest(AUTHENTICATE_USER, authSetCookie)

```

**Comment by klis87** [comment]
Which `redux-saga-requests` version do you use?

You got error in the following place: https://github.com/klis87/redux-saga-requests/blob/master/packages/redux-saga-requests/src/middleware.js#L34

It means that for some reason a related to your response action   request is not found in `requestMap`. One of the reasons it could be:
- you have older version or this library
- for some reason there is a response object like success dispatched without corresponding request action
- for some reason response actions are duplicated, so you could have sequence: `PASSWORD_LOGIN`, `PASSWORD_LOGIN_SUCCESS`,` PASSWORD_LOGIN_SUCCESS`, then the last action would trigger this error

So, you need to investigate what actions are dispatched on the server before getting this error, then the question will be answered what could be the culprit.

**Comment by klis87** [comment]
Closing due to inactivity. Using next.js with this library is also to be reconsidered as `redux-saga-requests` has 1st SSR support with universal code
